// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRYKT8SxQP8FwmBqmQbK9IbjRt5G9icWk',
    appId: '1:208460228500:web:6c6661c2d66a5c427c9181',
    messagingSenderId: '208460228500',
    projectId: 'softdevuas-f19ad',
    authDomain: 'softdevuas-f19ad.firebaseapp.com',
    storageBucket: 'softdevuas-f19ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaepvxViEQWI58Jsl7doY25q7fXPl1EzI',
    appId: '1:208460228500:android:df2c67f4a92ee2e47c9181',
    messagingSenderId: '208460228500',
    projectId: 'softdevuas-f19ad',
    storageBucket: 'softdevuas-f19ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO1gmzDDlUb8J_TWirzYlu60pPTYS38rw',
    appId: '1:208460228500:ios:daa669b2d640f5b67c9181',
    messagingSenderId: '208460228500',
    projectId: 'softdevuas-f19ad',
    storageBucket: 'softdevuas-f19ad.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO1gmzDDlUb8J_TWirzYlu60pPTYS38rw',
    appId: '1:208460228500:ios:daa669b2d640f5b67c9181',
    messagingSenderId: '208460228500',
    projectId: 'softdevuas-f19ad',
    storageBucket: 'softdevuas-f19ad.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRYKT8SxQP8FwmBqmQbK9IbjRt5G9icWk',
    appId: '1:208460228500:web:478003c24b192ee17c9181',
    messagingSenderId: '208460228500',
    projectId: 'softdevuas-f19ad',
    authDomain: 'softdevuas-f19ad.firebaseapp.com',
    storageBucket: 'softdevuas-f19ad.appspot.com',
  );
}
